//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/12/2018 11:25:52
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel.Repository
{
    
    /// <summary>
    /// Repository d'accès aux objets du type Person
    /// </summary>
    internal partial class PersonRepository : BaseRepository<MMPModel.MMPEntities, MMPModel.Person>
    {
    
    }
}
