//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/12/2018 14:53:24
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Classe représentant un livre
    /// </summary>
    public partial class Book : IEntity
    {
        #region Propriétés simples
    
    	/// <summary>
        /// L&apos;identifiant unique du livre
        /// </summary>
        public int Id { get; set; }
    
    	/// <summary>
        /// Le titre du livre
        /// </summary>
        public string Title { get; set; }
    
    	/// <summary>
        /// Le type du livre
        /// </summary>
        public BookEnumType Type { get; set; }

        #endregion

        #region Propriétés de navigation
    
    	/// <summary>
        /// L&apos;auteur du livre
        /// </summary>
        public virtual Person Author { get; set; }

        #endregion

    }
}
