//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/12/2018 11:25:23
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// Implémentation du DbContext
    /// </summary>
    public partial class MMPEntities : DbContext
    {
    
        #region Constructeurs
        
    	/// <summary>
    	/// Initialise un nouvel objet MMPEntities à l'aide de la chaîne de connexion trouvée dans la section 'MMPEntities' du fichier de configuration d'application.
    	/// </summary>
    	public MMPEntities()
            : base("name=MMPEntities")
        {
    		OnContextCreated();
        }
        
    	/// <summary>
    	/// Initialise un nouvel objet MMPEntities.
    	/// </summary>
        /// <param name="nameOrConnectionString">Le nom ou la chaine de connexion à la base de données.</param>
    	public MMPEntities(string nameOrConnectionString) 
            : base(nameOrConnectionString)
    	{
    		OnContextCreated(nameOrConnectionString);
    	}

        #endregion

        #region Méthodes partielles
    	
    	/// <summary>
        /// Méthode appellée une fois le DbContext créé
        /// </summary>
        partial void OnContextCreated();
    
        
        /// <summary>
        /// Méthode appellée une fois le DbContext créé
        /// </summary>
        /// <param name="nameOrConnectionString">Le nom ou la chaine de connexion à la base de données.</param>
        partial void OnContextCreated(string nameOrConnectionString);

        #endregion

        #region Propriétés DbSet
    
    	/// <summary>
    	/// DbSet d'accès aux entités du type Person
    	/// </summary>
        public virtual DbSet<Person> People { get; set; }

        #endregion

    }
}
