//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/13/2018 09:43:47
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel
{
    /// <summary>
    /// Interface implémentée par toutes les entités du modèle
    /// </summary>
    public interface IEntity
    {
    }
}
