//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/12/2018 11:25:31
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Person
    {
    #region Propriétés simples
    
    	/// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public int Id { get; set; }
    
    	/// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public string FullName { get; set; }
    
    	/// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public string Email { get; set; }
    
    	/// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public System.DateTime CreatedOn { get; set; }

    #endregion

    }
}
