//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/12/2018 14:53:24
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Classe représentant une personne
    /// </summary>
    public partial class Person : IEntity
    {
        #region Constructeurs
    
    	/// <summary>
    	/// Initialise un nouvel objet Person
    	/// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Email = "noreply@mail.com";
            this.Books = new HashSet<Book>();
        }

        #endregion

        #region Propriétés simples
    
    	/// <summary>
        /// L&apos;identifiant unique de la personne
        /// </summary>
        public int Id { get; set; }
    
    	/// <summary>
        /// Le nom complet de la personne
        /// </summary>
        public string FullName { get; set; }
    
    	/// <summary>
        /// L&apos;adresse email de la personne
        /// </summary>
        public string Email { get; set; }
    
    	/// <summary>
        /// La date de création de la personne dans le système
        /// </summary>
        public System.DateTime CreatedOn { get; set; }

        #endregion

        #region Propriétés de navigation
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    
    	/// <summary>
        /// La liste des livres écrits par la personne
        /// </summary>
        public virtual ICollection<Book> Books { get; set; }

        #endregion

    }
}
