//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle. @04/13/2018 09:46:15
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPModel.Service
{
    using System;
    using System.Collections.Generic;
    using Mehdime.Entity;
    
    /// <summary>
    /// Service d'accès aux objets du type User
    /// </summary>
    public partial class UserService : BaseService
    {
    
        #region Constructeur
    
    	/// <summary>
    	/// Initialise un nouvel objet UserService
    	/// </summary>
        internal UserService(IDbContextScopeFactory scopeFactory) : base(scopeFactory)
        {
        }

        #endregion

    }
}
